# Generated by Django 5.2.4 on 2025-07-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="diagnosis_images/")),
                ("disease_name", models.CharField(max_length=200)),
                ("severity", models.CharField(max_length=250)),
                ("affected_part", models.CharField(max_length=500)),
                ("confidence", models.FloatField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
