# Generated by Django 5.2.4 on 2025-07-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
